# ~/.config/kitty/kitty.conf

# theme
include ~/.config/kitty/kitty-themes/Belafonte_Day.conf
# font
font_family      JetBrainsMono Nerd Font
font_size        10.0

# window
window_padding_width 2
confirm_os_window_close 0
background_opacity 1

# tab bar
tab_bar_style    powerline
tab_bar_edge     bottom

# shell integration
shell_integration enabled

# launch tmux on start
shell tmux new-session -A -s main

# keybinds
map ctrl+v paste_from_clipboard
map ctrl+c copy_or_interrupt
