vim.keymap.set('n', '<leader>q', '<cmd>wqall<CR>', { desc = 'Write and quit all' })
vim.keymap.set('n', '<leader>Q', '<cmd>qall!<CR>', { desc = 'Quit all without saving' })
vim.keymap.set('n', '<leader>w', '<cmd>wall<CR>', { desc = 'Write all' })
vim.keymap.set('n', 'x', vim.diagnostic.setqflist, { desc = 'Open diagnostics in quickfix' })
vim.keymap.set('i', 'jj', '<Esc>')
vim.keymap.set({ 'n', 'v' }, 'ä', '{', { desc = 'Jump to previous paragraph' })
vim.keymap.set({ 'n', 'v' }, 'ö', '}', { desc = 'Jump to next paragraph' })
vim.keymap.set("v", "<", "<gv", { desc = "Indent left and reselect" })
vim.keymap.set("v", ">", ">gv", { desc = "Indent right and reselect" })
